### ISSUE TITLE
GUI string suggestions/questions

### ISSUE THREAD

**Issue by humdingerb** [threedeyes/STLover#1]
I have some suggestions:

* To be Haiku consistent, the "Ok" in dialogs should be "OK".
* In the "View" menu, "Show statistics" should be just "Statistics" so it fits in with the other items there and the tooltip on the icon in the toolbar.
* The tooltip for "Put on the Middle" should be the same as the menu item, i.e. "Move on the Middle" (again lower-casing?)

I'm not familiar with CAD or 3D printing apps, so I have a question:

* What's exactly the difference between "Move | To Center" and "Move | On the Middle" ("center" and "middle" should probably be lower-case)? Maybe it could be more descriptive to include "axes" here, like "Center on axes" if the object is moved, or "Center axes" if the axes are moved. I'm a bit fuzzy what exactly is moved, object or axes... (does it make a difference when there's only just one object).

**Comment by threedeyes** [comment]
> What's exactly the difference between "Move | To Center" and "Move | On the Middle"

To Center:
![2020-11-21_17-48](https://user-images.githubusercontent.com/2559260/99870860-f02dac00-2c21-11eb-8de3-5cdb909b090e.png)

Put on the middle:
![2020-11-21_17-48_1](https://user-images.githubusercontent.com/2559260/99870862-f15ed900-2c21-11eb-973d-b961e4811eb4.png)

**Comment by humdingerb** [comment]
Kitty Cat! :)

Ah, I understand. Maybe "Move to origin" and "Move to top of OXY plane" would be more descriptive.
Dumb question: should it be 0XY ('zero'XY)?

**Comment by threedeyes** [comment]
> Dumb question: should it be 0XY ('zero'XY)?

It's O (letter) - **O**rigin

![2020-11-21_23-53](https://user-images.githubusercontent.com/2559260/99878970-dc4f6d80-2c54-11eb-9adb-53a6fff041d8.png)

**Comment by humdingerb** [comment]
0h0, or better: Oho! :)
Makes sense, too.

**Comment by humdingerb** [comment]
Don't forget to update the catkeys at Polyglot. :)
Also, you may want to change the package description in the haikuports recipe to be a bit more detailed,maybe add a short list of main features and mention "3D printing" so people using HaikuDepot's search function find STLover.

**Comment by threedeyes** [comment]
> Don't forget to update the catkeys at Polyglot. :)

I remember

> Also, you may want to change the package description in the haikuports recipe to be a bit more detailed

This is the most difficult thing for me - I do not know English well )))

**Comment by humdingerb** [comment]
You know the app best. If you want, you can post a draft here and I proof-read and change the recipe.
