### ISSUE TITLE
Add orthographic projection mode

### ISSUE THREAD

**Issue by Lt-Henry** [threedeyes/STLover#17]
This is a common feature on every 3D viewer, it allows user to check geometry without perspective distortion. Also, it will allow for a future measure tool.

**Comment by Lt-Henry** [comment]
![screenshot7](https://user-images.githubusercontent.com/3853371/127787509-b669903c-6f63-4c09-8e48-78f40e7b3308.jpeg)

Almost there! but not ready for PR yet

**Comment by threedeyes** [comment]
Cool!
I'll draw an icon for this feature in the general style then. Okay?

**Comment by Lt-Henry** [comment]
Of course! I've just drawn a very simple one as "reference" :D

I was wondering if this ortho/perspective toggle is well placed there, or perhaps you prefer to place it elsewhere

**Comment by threedeyes** [comment]
I think that's where he belongs
