### ISSUE TITLE
Label axes in view

### ISSUE THREAD

**Issue by humdingerb** [threedeyes/STLover#2]
It'd be nice to have a red/green/yellow coloured label for the X/Y/Z axes at the end of axes arrows.

**Comment by threedeyes** [comment]
Added in https://github.com/threedeyes/STLover/commit/d03d69bd41f73b99a2da69c03ce367af5062ad51

![axes](https://user-images.githubusercontent.com/2559260/100517317-8ab75d80-31d5-11eb-9d9f-8528197cb625.png)
