### ISSUE TITLE
Darker colour for Y-axis

### ISSUE THREAD

**Issue by humdingerb** [threedeyes/STLover#3]
I have a slight yellow-green weakness. Bright yellow and green are difficult for me to distinguish. If you don't want to change one to blue, maybe making the green a bit darker would be nice.

**Comment by threedeyes** [comment]
I want to add color customization for some objects: background color, axis color, light color, etc.

**Comment by humdingerb** [comment]
+1

**Comment by humdingerb** [comment]
Hmm... maybe keep the axes colours fixed to keep all the toolbar icons consistent.
If you go with the legend-view (see #5), the axes will be nicely visible for all custom background/light/etc colours.
If you go with red/green/blue, don't forget to update the colours of the toolbar icons. You should add the IOM files of the icons to the github, then people could PR changes.

**Comment by Lt-Henry** [comment]
> Hmm... maybe keep the axes colours fixed to keep all the toolbar icons consistent.
> If you go with the legend-view (see #5), the axes will be nicely visible for all custom background/light/etc colours.
> If you go with red/green/blue, don't forget to update the colours of the toolbar icons. You should add the IOM files of the icons to the github, then people could PR changes.

Is there a color-blind friendly palette? Solarized, Nord, Dracula....?
