### ISSUE TITLE
Scale axes arrows when zooming

### ISSUE THREAD

**Issue by humdingerb** [threedeyes/STLover#5]
When you zoom into an object, the arrow tips (and maybe one day their label (#2)) disappear from view. Would it be possible to scale the axes arrows so that the arrow tips are always visible?

**Comment by threedeyes** [comment]
Hm. Wouldn't it be better to make a legend like this?
![2020-11-21_18-29](https://user-images.githubusercontent.com/2559260/99871557-87e1c900-2c27-11eb-8fbc-a15d67740972.png)

**Comment by humdingerb** [comment]
Even better!

**Comment by Lt-Henry** [comment]
> Hm. Wouldn't it be better to make a legend like this?
> ![2020-11-21_18-29](https://user-images.githubusercontent.com/2559260/99871557-87e1c900-2c27-11eb-8fbc-a15d67740972.png)

What software is that? I thought It was meshlab, but it is not.

Good idea, btw.

**Comment by threedeyes** [comment]
> What software is that? I thought It was meshlab, but it is not.

http://www.glc-player.net/

**Comment by Lt-Henry** [comment]
Ok, got this. It is very similar to glc screenshot, with axis name billboard too (always facing camera). Here some thoughts:

- Axis colors are.... wrong? x,y,z -> r,g,b
- Axis names are being done with lines... it does the job but it is ugly. Would be nicer using a bitmap (ie: Blender)
- Would be nice to hide names whenever its axis is perpendicular to camera, if not, it results a bit annoying.
- I have eliminated axis arrow, I have no problem at all with them, I just wanted to had something working as soon as poosible. However, in my opinion, are no longer needed at such a small scale.

What do you think? May I clean the code and push it?

![screenshot3](https://user-images.githubusercontent.com/3853371/103489405-9faa9080-4e14-11eb-92bb-6133f6341939.png)

**Comment by threedeyes** [comment]
Why not? You are wellcome.
