### ISSUE TITLE
Add BSpinners and BSliders to move/scale/rotate dialogs

### ISSUE THREAD

**Issue by humdingerb** [threedeyes/STLover#8]
Once #7 is done, it'd be nice to add sliders for quick manipulation and spinners for exact value entry by mouse.

**Comment by threedeyes** [comment]
At the moment I have made rotations using sliders. But I don't think it is reasonable to use spinners - they are good for inputting integer values, not floating point values.
![screenshot165](https://github.com/user-attachments/assets/b845b3b5-03ee-43b8-92a9-48282d81d50e)

**Comment by humdingerb** [comment]
Yeah, I think that's right.
I wish BSlider had an optional BTextControl (with or without spinners) that showed the current value and also allowed the user to enter a specific value...

**Comment by threedeyes** [comment]
> that showed the current value

The current value is already displayed here:
![screenshot1](https://github.com/user-attachments/assets/41c14c86-06fa-40bf-9192-90c919c510fc)

**Comment by humdingerb** [comment]
Yeah, I know. :)
The important part is that a BTextControl at the same time allows the user to enter a specific value.

Currently the only way to fine-tune a value, say you want exactly 94°, is to use the cursor keys while the slider knob is active. A way some users may not be aware of.

**Comment by threedeyes** [comment]
![outputfile-2024-12-07](https://github.com/user-attachments/assets/81402e88-0844-4236-a93a-e44747d0fd08)

**Comment by humdingerb** [comment]
Perfect! \o/

**Comment by threedeyes** [comment]
Fixed in https://github.com/threedeyes/STLover/commit/238861464da3517d0fadd3f0b8f76cda8176f7e0
